apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.n8n.storage.size }}
