apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  POSTGRES_NON_ROOT_USER: {{ .Values.postgres.credentials.nonRootUser }}
  POSTGRES_NON_ROOT_PASSWORD: {{ .Values.postgres.credentials.nonRootPassword }}
